spring.application.name=bookReview

# port
server.port = 8081

# PostGreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/bookreview
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Let hibernate auto-create/update for now
spring.jpa.hibernate.ddl-auto=update

